# Copyright © 2026 Rafail Medzhidov <rafayt323@gmail.com>
# SPDX-License-Identifier: MIT

from typing import final

import attrs


@final
@attrs.define(slots=True, frozen=True)
class GeneratedExercise:
    """Represents an exercise generated by an LLM."""

    sentence: str
    reference_translation: str
    words_used: list[str] = attrs.field(factory=list)
    grammar_used: list[str] = attrs.field(factory=list)


@final
@attrs.define(slots=True, frozen=True)
class ExerciseCheckResult:
    """Represents the evaluation result of a user-submitted translation."""

    is_correct: bool
    feedback: str
    corrected_sentence: str
